apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  AUTH_SECRET: {{ .Values.secrets.authSecret | quote }}
