apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
  AUTH_SECRET: "super-secret-key-change-in-production"
  RABBITMQ_DEFAULT_PASS: "guest"
